In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 6])

In [3]:
a

array([1, 2, 3, 4, 6])

In [4]:
a.shape

(5,)

In [5]:
a.dtype

dtype('int32')

In [6]:
b = np.array([[1.0,2.0,3.0,5.0],[3.0,5.0,7.0,9.0]])

In [7]:
b.shape

(2, 4)

In [8]:
b.dtype

dtype('float64')

In [9]:
print(a.ndim, b.ndim)

1 2


In [10]:
print(a.size, b.size)

5 8


In [11]:
print(a.itemsize, b.itemsize)

4 8


In [12]:
print("total size of a & b: ", a.size*a.itemsize, b.size*b.itemsize)

total size of a & b:  20 64


In [13]:
print("total size of a & b: ", a.nbytes, b.nbytes)

total size of a & b:  20 64


In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [15]:
a.shape

(2, 7)

In [16]:
i, j = a.shape

In [17]:
for r in range(i):
    for c in range(j):
        print(a[r][c], end="\t")
    print()

1	2	3	4	5	6	7	
8	9	10	11	12	13	14	


In [18]:
a[:,1:-2:2]

array([[ 2,  4],
       [ 9, 11]])

In [19]:
a[1,5] = 30

In [20]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 30, 14]])

In [21]:
a[:,2]= [1,2]

In [22]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 30, 14]])

In [23]:
np.zeros((2, 3, 3, 2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [24]:
np.ones((4,2,2,2))

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [25]:
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [26]:
np.full_like(a, 9)

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [27]:
np.random.rand(4, 2)

array([[0.46283372, 0.00437302],
       [0.71249305, 0.30564823],
       [0.71175099, 0.1067191 ],
       [0.76650028, 0.86326686]])

In [28]:
np.random.random_sample(a.shape)

array([[0.42602328, 0.31002936, 0.27280871, 0.77372449, 0.00330607,
        0.64326991, 0.23045485],
       [0.56591441, 0.19082797, 0.99468928, 0.29527688, 0.27307207,
        0.42730505, 0.84565855]])

In [29]:
np.random.randint(-3, 7, size=(3,3))

array([[ 2, -1,  1],
       [ 5, -1, -1],
       [ 4,  1,  2]])

In [30]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
arr = np.repeat(np.array([[1,2,3],[7,8,9]]), 6, axis=0)

In [32]:
arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [7, 8, 9],
       [7, 8, 9],
       [7, 8, 9],
       [7, 8, 9],
       [7, 8, 9],
       [7, 8, 9]])

In [33]:
t1 = np.ones((5,5))

In [34]:
t1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
t1zeros = np.zeros((3,3))

In [36]:
t1zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
t1zeros[1,1]=9

In [38]:
t1[1:-1,1:-1]=t1zeros

In [39]:
t1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
n1 = np.array([1,2,3])

In [41]:
n2 = np.array([0,9])

In [42]:
n2 = n1

In [43]:
n1

array([1, 2, 3])

In [44]:
n2

array([1, 2, 3])

In [45]:
n2[0] = 9

In [46]:
n2

array([9, 2, 3])

In [47]:
n1

array([9, 2, 3])

In [48]:
m1 = np.array([1,2,3])
m2 = m1.copy() # No object mutation

In [49]:
m2[0] = 99

In [50]:
print(m1, m2)

[1 2 3] [99  2  3]


In [51]:
x = np.array([1, 2, 3, 4])

In [52]:
print('Addition:', x+2)

Addition: [3 4 5 6]


In [53]:
print('Subtraction:', x-2)

Subtraction: [-1  0  1  2]


In [54]:
print('multiplication: ', x * 7)

multiplication:  [ 7 14 21 28]


In [55]:
print('Division: ', x/2)

Division:  [0.5 1.  1.5 2. ]


In [56]:
print("Sin of value", 1/np.sin(x))

Sin of value [ 1.18839511  1.09975017  7.0861674  -1.32134871]


In [57]:
l1 = np.full((2,3), 2)
l2 = np.full((3, 2), 4)
np.matmul(l1,l2)

array([[24, 24],
       [24, 24]])

In [58]:
# Find the determinate
c = np.identity(3)
np.linalg.det(c)

1.0

In [59]:
stats = np.array([[1,2,3],[4,5,6]]) 

In [60]:
np.mean(stats, axis=1)

array([2., 5.])

In [61]:
np.min(stats, axis=1)

array([1, 4])

In [62]:
np.max(stats, axis=1)

array([3, 6])

In [63]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [64]:
b4 = np.array([[1,2,3,4],[5,6,7,8]])
atr = b4.reshape((8,1))

In [65]:
atr

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [66]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])

In [67]:
print(v1.ndim, v2.ndim)

1 1


In [68]:
np.vstack([v2, v1])

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [69]:
np.hstack([v2, v1])

array([ 6,  7,  8,  9, 10,  1,  2,  3,  4,  5])

In [70]:
filedata = np.genfromtxt('sales_per_week.csv', delimiter=",",dtype="int32")
# filedata.astype("int64") #alternative approach

In [71]:
filedata

array([[1, 3, 4, 5, 6, 1, 0],
       [1, 2, 2, 4, 4, 1, 0],
       [1, 1, 4, 5, 6, 0, 1],
       [1, 1, 5, 6, 5, 0, 0]])

In [72]:
filedata[filedata < 3]

array([1, 1, 0, 1, 2, 2, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0])

In [73]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,3]]

array([2, 4])

In [74]:
np.any(filedata > 5, axis=1)

array([ True, False,  True,  True])

In [75]:
np.all(filedata > 5, axis=0)

array([False, False, False, False, False, False, False])

In [76]:
((filedata > 2) & (filedata <4))

array([[False,  True, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [77]:
arr_num = np.arange(1, 26).reshape((5,5))
arr_num

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [78]:
arr_num[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [79]:
arr_num[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [80]:
arr_num[[0,4,3],3:]

array([[ 4,  5],
       [24, 25],
       [19, 20]])