In [1]:
import numpy as np

In [2]:
# initial data

num_list_1 = [1,2,3,4,5,6]
num_list_2 = [[1,2,3],[4,5,6]]
print("Data in number list 1 and 2:", num_list_1, "&", num_list_2)
print("type of number list 1 and 2:", type(num_list_1), "&", type(num_list_2))

Data in number list 1 and 2: [1, 2, 3, 4, 5, 6] & [[1, 2, 3], [4, 5, 6]]
type of number list 1 and 2: <class 'list'> & <class 'list'>


In [3]:
# list to numpy array

np_arr_1 = np.array(num_list_1)
np_arr_2 = np.array(num_list_2)

print("Numpy data array 1 and 2 :", np_arr_1, "&", np_arr_2)
print("Data type:", type(np_arr_1),"&",type(np_arr_2))

Numpy data array 1 and 2 : [1 2 3 4 5 6] & [[1 2 3]
 [4 5 6]]
Data type: <class 'numpy.ndarray'> & <class 'numpy.ndarray'>


In [4]:
# get specified range of data


np.arange(1, 10, 3)

array([1, 4, 7])

In [5]:
# Zero matrix

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# Zero matrix n dimension array 
# parameters defines as (rows, columns)

np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# One's matrix

np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# Getting linear space / equal interval numbers
# (Min number, Max number, Number of values to be returned)

print("Example 1:", np.linspace(1, 5, 5))

print("Example 2:", np.linspace(1, 5, 6))

print("Example 3:", np.linspace(-1, -5, 6))

print("Example 4:", np.linspace(1, -5, 6))

print("Example 5:", np.linspace(-1, 5, 6))

print("Example 6:", np.linspace(1, 5, 3))

Example 1: [1. 2. 3. 4. 5.]
Example 2: [1.  1.8 2.6 3.4 4.2 5. ]
Example 3: [-1.  -1.8 -2.6 -3.4 -4.2 -5. ]
Example 4: [ 1.  -0.2 -1.4 -2.6 -3.8 -5. ]
Example 5: [-1.   0.2  1.4  2.6  3.8  5. ]
Example 6: [1. 3. 5.]


In [9]:
# Identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# Random distributions of data
# Uniform distrubtion

np.random.rand(4, 3)

array([[0.02731536, 0.60783402, 0.60984177],
       [0.91285051, 0.41473047, 0.43336455],
       [0.49869957, 0.88855908, 0.83707085],
       [0.50109399, 0.93253566, 0.54758619]])

In [11]:
# Random of normal distribution
# mean is 0 and variance is 1

np.random.randn(2, 3)

array([[ 0.03199756, -0.57474703, -0.28418634],
       [ 0.88309433, -1.16470979, -1.09911877]])

In [12]:
# Unifrom distribution

print("Example 1:\n", np.random.randint(1, 11, 3))
print("*"*10)
print("Example 2:\n ", np.random.randint(1, 11, (2,3)))

Example 1:
 [8 5 7]
**********
Example 2:
  [[ 5 10  5]
 [ 3  9  7]]


In [13]:
# Seed is used to set the random state, so that random also set to reproduced
# Some random 42 is the Hitchhiker's Guide to the Galaxy by Douglas Adams.

np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [14]:
# Reshape

arr = np.arange(0, 25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
# Aggreate function


r_arr = np.random.randint(0, 101, 10)
print("data: ", r_arr)
print("Minimum and Maximum:", np.min(r_arr), "&", np.max(r_arr))
print("Index position of Minimum and Maximum:", np.argmin(r_arr), "&", np.argmax(r_arr))
print("Sum:", np.sum(r_arr), "(or)", r_arr.sum())
print("Mean:", np.mean(r_arr), "(or)", r_arr.mean())

data:  [82 86 74 74 87 99 23  2 21 52]
Minimum and Maximum: 2 & 99
Index position of Minimum and Maximum: 7 & 5
Sum: 600 (or) 600
Mean: 60.0 (or) 60.0




---
<center>
<h1>Selection & Ranging</h1>
</center>

---


In [27]:
arr2 = np.arange(0, 11)
print("Data", arr2)
print("Data at position at 9: ", arr2[9])
print("Example 1: ", arr2[0:9])

Data [ 0  1  2  3  4  5  6  7  8  9 10]
Data at position at 9:  9
Example 1:  [0 1 2 3 4 5 6 7 8]


In [29]:
# Boradcasting the array

arr3 = np.arange(0, 11)
print("Before - Boradcasting", arr3)
arr3[0:5] = 199
print("After - Boradcasting", arr3)

Before - Boradcasting [ 0  1  2  3  4  5  6  7  8  9 10]
After - Boradcasting [199 199 199 199 199   5   6   7   8   9  10]


In [32]:
# Slicing and broadcasting

slice_arr3 = arr3[2:7]
print("Slice of arr3", slice_arr3)
slice_arr3[:] = 42
print("After broadcasting Slice of arr3 and original arr3:", slice_arr3, "&", arr3)

Slice of arr3 [199 199 199   5   6]
After broadcasting Slice of arr3 and original arr3: [42 42 42 42 42] & [199 199  42  42  42  42  42   7   8   9  10]


In [34]:
# Deep copy 

slice_arr3_v2 = np.copy(arr3[2:7])
print("Slice of arr3 version 2", slice_arr3_v2)
slice_arr3_v2[:] = 153
print("After broadcasting Slice of arr3 version2 and original arr3:", slice_arr3_v2, "&", arr3)

Slice of arr3 version 2 [42 42 42 42 42]
After broadcasting Slice of arr3 version2 and original arr3: [153 153 153 153 153] & [199 199  42  42  42  42  42   7   8   9  10]


In [54]:
# 2 dimension array

arr_2d = np.array([[1,2,3],[3,3,3],[9,8,7]])
print("arr_2d: ", arr_2d)
print("Shape:", arr_2d.shape)
print("Element at 0th row & 1st column: ", arr_2d[0,1], "(or)", arr_2d[0][1])
print("Slice 1:", arr_2d[1:, :2])
print("Slice 1:", arr_2d[:2, :])

arr_2d:  [[1 2 3]
 [3 3 3]
 [9 8 7]]
Shape: (3, 3)
Element at 0th row & 1st column:  2 (or) 2
Slice 1: [[3 3]
 [9 8]]
Slice 1: [[1 2 3]
 [3 3 3]]


In [63]:
arr_3 = np.arange(0, 10)
print(arr_3)
print("Filter data greater than 5:", arr_3[arr_3>5])
print("Filter data greater than 5:", np.where(arr_3>5))

[0 1 2 3 4 5 6 7 8 9]
Filter data greater than 5: [6 7 8 9]
Filter data greater than 5: (array([6, 7, 8, 9]),)




---
<center>
<h1>
<b>Airthematic Operations</b>
</h1>
</center>

---


In [75]:
arr_a = np.arange(1, 11)
arr_b = np.arange(10, 0, -1)

print(arr_a, arr_b)
print("Addition: ", arr_a + arr_b)
print("Subtraction: ", arr_a - arr_b)
print("Division example1: ", arr_a / arr_b)
print("Division example2: ", arr_b / (arr_a-1))

[ 1  2  3  4  5  6  7  8  9 10] [10  9  8  7  6  5  4  3  2  1]
Addition:  [11 11 11 11 11 11 11 11 11 11]
Subtraction:  [-9 -7 -5 -3 -1  1  3  5  7  9]
Division example1:  [ 0.1         0.22222222  0.375       0.57142857  0.83333333  1.2
  1.75        2.66666667  4.5        10.        ]
Division example2:  [       inf 9.         4.         2.33333333 1.5        1.
 0.66666667 0.42857143 0.25       0.11111111]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in true_divide
  


In [85]:
print("Square root:", np.sqrt(arr_b))
print("Trignometry:", np.sin(arr_a))
print("Logrithums:", np.log(arr_a))
print("Mean/Avg:", np.mean(arr_a))
print("Variance:", np.var(arr_a))
print("Standard deviation:", np.std(arr_a))

Square root: [3.16227766 3.         2.82842712 2.64575131 2.44948974 2.23606798
 2.         1.73205081 1.41421356 1.        ]
Trignometry: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
Logrithums: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
Mean/Avg: 5.5
Variance: 8.25
Standard deviation: 2.8722813232690143


In [89]:
arr2d = np.arange(0, 25).reshape(5, 5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [91]:
#Working with 2d array
print("Sum of rows", arr2d.sum(axis=1))
print("Sum of columns", arr2d.sum(axis=0))

Sum of rows [ 10  35  60  85 110]
Sum of columns [50 55 60 65 70]


# Recap

In [98]:
uniform_dist_arr = np.arange(1, 101)/100
uniform_dist_arr.reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [101]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [111]:
mat2d = np.arange(1, 26).reshape(5, 5)

mat2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [112]:
mat2d[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [114]:
mat2d[4]

array([21, 22, 23, 24, 25])

In [115]:
np.random.seed(101)
np.random.rand(1)

array([0.51639863])