# Some random practice problems

In [1]:
import numpy as np

In [2]:
t1 = np.arange(1, 11).reshape(2, 5)
t2 = np.random.randint(1, 100, 12).reshape(3, 4)

In [3]:
print("GIVEN\n\n", t1, "\n\n", t2)
print("SUM.t1", t1.sum(axis = 1), t1.sum(axis = 0), t1.sum())
print("MEAN.t1", t1.mean(axis = 1), t1.mean(axis = 0), t1.mean())
print("MAX.t1", t1.max(axis = 1), t1.max(axis = 0), t1.max())
print("MIN.t1", t1.min(axis = 1), t1.min(axis = 0), t1.min())
print("ARGMAX.t2", t2.argmax(axis = 1), t2.argmax(axis = 0), t2.argmax())
print("ARGMIN.t2", t2.argmax(axis = 1), t2.argmax(axis = 0), t2.argmax())

GIVEN

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

 [[64 31 59  4]
 [ 2 80 30 83]
 [89  6 72 51]]
SUM.t1 [15 40] [ 7  9 11 13 15] 55
MEAN.t1 [3. 8.] [3.5 4.5 5.5 6.5 7.5] 5.5
MAX.t1 [ 5 10] [ 6  7  8  9 10] 10
MIN.t1 [1 6] [1 2 3 4 5] 1
ARGMAX.t2 [0 3 0] [2 1 2 1] 8
ARGMIN.t2 [0 3 0] [2 1 2 1] 8


In [4]:
t3 = np.random.randint(1, 1000, 20).reshape(4, 5)
p = np.sum(np.random.randint(1, 100, 5))
print(t3, p)

[[894 217 748 303 954]
 [242 201 755 523 758]
 [779 619 751 888 141]
 [896 820 302 938  77]] 288


In [5]:
np.column_stack(np.where(t3 > p))

array([[0, 0],
       [0, 2],
       [0, 3],
       [0, 4],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3]], dtype=int64)

In [6]:
t4 = np.random.randint(1, 25, 25).reshape(5, 5)
print(t4)
x = np.sum(t4[[0,1,2,3,4],[0,1,2,3,4]])
print(x)
t4 * x

[[ 5 19 13 13 12]
 [ 8  6  8  5 18]
 [16  3 12 15 21]
 [ 5  9 14 20  5]
 [ 2 21  8  6  2]]
45


array([[225, 855, 585, 585, 540],
       [360, 270, 360, 225, 810],
       [720, 135, 540, 675, 945],
       [225, 405, 630, 900, 225],
       [ 90, 945, 360, 270,  90]])

In [7]:
i = np.random.randint(0, 4)
j = i - 1
t5 = np.random.randint(0, 255, 25).reshape(5, 5)
k = t5[i, j]
print(k, t5 * k)

65 [[ 8450  7605  2145  7800  5590]
 [ 6695  2600  8190 11180 13455]
 [ 6825  4225  9555  4160  1105]
 [14950   260 10985  2145  8645]
 [ 4550  1235 11245  6370 14495]]


In [8]:
t6 = np.random.randint(0, 99, 9).reshape(3, 3)
print(t6, t6[[0,1,2],[0,1,2]].reshape(3,1))

[[ 3  3 28]
 [75 57 94]
 [41 11 64]] [[ 3]
 [57]
 [64]]


In [9]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')])
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student)
print(a, a.dtype)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)] [('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
